import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/Sidebar";
import { MachineInfoProvider } from '../Providers/MachineInfoProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "稼働管理システム",
  description: "Generated by create next app",
};

// Sidebarはここに書く。他にここに書くべきものは？HOMEとの違い。
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // get 
  // provider

  return (
    <html lang="ja">
      <MachineInfoProvider>
        <body className={"flex ${inter.className}"}>
          <Sidebar />
          <div className="w-full">
            <div className="ml-[350px]"> {children}</div>
          </div>
        </body>
      </MachineInfoProvider>
    </html>
  );
}
